# vi:ts=2:sw=2:et:ft=yaml
---
language: python
python: "3.8"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  # Test functionality with default values
  - ansible-playbook tests/test_defaults.yml -i localhost, --syntax-check
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local -b

  - ansible-playbook tests/test_config.yml -i localhost, --syntax-check
  - ansible-playbook tests/test_config.yml -i localhost, --connection=local -b

  # Test upgrade
  - ansible-playbook tests/test_defaults.yml -i localhost, --connection=local -b
